{% set version = "1.5.1" %}

package:
  name: conda-smithy
  version: {{ version }}

source:
  fn: conda-smithy-v{{ version }}.tar.gz
  url: https://github.com/conda-forge/conda-smithy/archive/v{{ version }}.tar.gz
  sha256: 606a69b8cfbf680a2701bafa08d76c68203d841cfe2a3f3fcecb16ca12104cd3

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - feedstocks = conda_smithy.feedstocks:main
    - conda-smithy = conda_smithy.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - conda-build-all
    - conda
    - conda-build >=1.21.12
    - jinja2
    - requests
    - pycrypto
    - gitpython
    - pygithub <2
    - ruamel.yaml

test:
  imports:
    - conda_smithy
    - conda_smithy.ci_register
    - conda_smithy.configure_feedstock
  commands:
    - conda smithy --help

about:
  home: https://github.com/conda-forge/conda-smithy
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: The tool for managing conda-forge feedstocks

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
