{% set version = "0.7.1" %}

package:
  name: conda-smithy
  version: {{ version }}

source:
  git_url: https://github.com/conda-forge/conda-smithy.git
  git_tag: v{{ version }}

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - conda-build-all
    - conda
    - conda-build
    - jinja2
    - requests
    - pycrypto
    - gitpython
    - pygithub <2
    - ruamel.yaml

test:
    imports:
        - conda_smithy
        - conda_smithy.ci_register
        - conda_smithy.configure_feedstock
    commands:
        - conda smithy --help

about:
    home: https://github.com/conda-forge/conda-smithy
    license: BSD 3
    summary: The tool for managing conda-forge feedstocks

extra:
    recipe-maintainers:
        - pelson
