{% set version = "3.44.1" %}
{% set python_min = python_min|default("0.1a0") %}

package:
  name: conda-smithy
  version: {{ version }}

source:
  url: https://github.com/conda-forge/conda-smithy/releases/download/v{{ version }}/conda_smithy-{{ version }}.tar.gz
  sha256: 3970664136bc5c4d9903c290fbd7e74652781b7db31bd2cc13f946069c825ce4

build:
  number: 0
  noarch: python
  string: unix_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [unix]
  string: win_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}   # [win]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
    - rm -f "${PREFIX}/bin/conda"           # [not win]
    - del /f /q "%PREFIX%\\Scripts\\conda"  # [win]
  entry_points:
    - feedstocks = conda_smithy.feedstocks:main
    - conda-smithy = conda_smithy.cli:main

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools >=45
    - setuptools-scm >=8.1
    - tomli >=1.0.0
  run:
    - __unix                          # [unix]
    - __win                           # [win]
    - python >={{ python_min }}
    - setuptools
    - conda >=4.2
    - conda-build >=24.3
    - conda-package-handling >=1.9.0
    - jinja2
    - requests
    - pycryptodome
    - gitpython
    - git                             # [unix]
    # TODO: Both `git` & `m2-git` on Windows have problems.
    #       For now, install neither. Hopefully we can find
    #       a better solution in the future.
    #- m2-git                          # [win]
    - pygithub >=2,<3
    - ruamel.yaml >=0.16
    - conda-forge-pinning
    - vsts-python-api
    - toolz
    - scrypt
    - license-expression
    - libarchive
    - tomli >=1.0.0  # for python <3.11, can remove in the future
    - backports.strenum
    - cirun >=0.30
    - exceptiongroup
    - jsonschema
    - rattler-build-conda-compat >=1.2.0,<2.0.0a0
  run_constrained:
    # For more details about `shellcheck`, please see this issue.
    # xref: https://github.com/conda-forge/conda-smithy-feedstock/issues/248
    - shellcheck

test:
  imports:
    - conda_smithy
    - conda_smithy.ci_register
    - conda_smithy.configure_feedstock
  requires:
    - python ={{ python_min }}
    - mock
    - pytest
    - pytest-cov
    - pydantic >=2,<3
  source_files:
    - tests/
  commands:
    - conda smithy --help
    # Run the tests but ignore tests that fail at the time of writing.
    - >- 
      pytest tests 
      --ignore tests/test_anaconda_token_rotation.py 
      --ignore tests/test_cli.py 
      --ignore tests/test_configure_feedstock.py 
      -k "not test_maintainer_team_exists"

about:
  home: https://github.com/conda-forge/conda-smithy
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: The tool for managing conda-forge feedstocks

extra:
  recipe-maintainers:
    - conda-forge/core
