{% set version = "3.55.0" %}

package:
  name: conda-smithy
  version: {{ version }}

source:
  # url: https://github.com/conda-forge/conda-smithy/releases/download/v{{ version }}/conda_smithy-{{ version }}.tar.gz
  url: https://github.com/conda-forge/conda-smithy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d4c86bf58795f5bc78ea996351de82de43f1e8e84e9e42c43ce797eb6a6afeff
  patches:
    # backport of https://github.com/conda-forge/conda-smithy/pull/2468
    - patches/0001-Revert-fix-unset-these-env-vars.patch
    - patches/0002-add-work-around-for-conda-build-inserting-spurious-v.patch
    - patches/0003-turn-debug-hint-into-reusable-context-manager.patch
    - patches/0004-avoid-hard-dependence-on-TEMP-environment-variable-o.patch

build:
  number: 0
  noarch: python
  string: {{ "win" if win else "unix" }}_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
    - rm -f "${PREFIX}/bin/conda"           # [not win]
    - del /f /q "%PREFIX%\\Scripts\\conda"  # [win]
  entry_points:
    - feedstocks = conda_smithy.feedstocks:main
    - conda-smithy = conda_smithy.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=45
    - setuptools-scm >=8.1
    - tomli >=1.0.0
  run:
    - __unix                          # [unix]
    - __win                           # [win]
    - python >={{ python_min }}
    - setuptools
    - conda >=4.2
    - conda-build >=24.3
    - conda-package-handling >=1.9.0
    - jinja2
    - requests
    - pycryptodome
    - gitpython
    - pygit2
    - git                             # [unix]
    # TODO: Both `git` & `m2-git` on Windows have problems.
    #       For now, install neither. Hopefully we can find
    #       a better solution in the future.
    #- m2-git                          # [win]
    - pygithub >=2,<3
    - ruamel.yaml >=0.16
    - conda-forge-pinning
    - vsts-python-api
    - toolz
    - scrypt
    - license-expression
    - libarchive
    - tomli >=1.0.0  # for python <3.11, can remove in the future
    - backports.strenum
    - cirun >=0.30
    - exceptiongroup
    - jsonschema
    # py-rattler's API subject to change, pin to minor
    - py-rattler >=0.22,<0.23
    - rattler-build-conda-compat >=1.4.5,<2.0.0a0
  run_constrained:
    # For more details about `shellcheck`, please see this issue.
    # xref: https://github.com/conda-forge/conda-smithy-feedstock/issues/248
    - shellcheck
    - pixi >=0.59.0
    - conda-recipe-manager >=0.9

test:
  imports:
    - conda_smithy
    - conda_smithy.ci_register
    - conda_smithy.configure_feedstock
  requires:
    # no python_min here to be able to test smithy as a downstream (e.g. conda-feedstock)
    - python
    - mock
    - pytest
    - pytest-cov
    - pydantic >=2.11,<3
    - conda-forge-tick      # [unix]
    - conda-souschef
    - conda-recipe-manager
    - git
  source_files:
    - tests/
    - pyproject.toml  # for pytest config bits
  commands:
    - conda smithy --help
    - pytest tests --ignore tests/test_anaconda_token_rotation.py --ignore tests/test_cli.py -k "not test_maintainer_team_exists and not test_github_actions_pins and not test_maintainer_exists and not test_lint_recipe_parses_spacing and not test_schema_no_empty_properties_for_bot"
    # test that rerender works
    - git clone https://github.com/conda-forge/conda-smithy-feedstock the_feedstock
    - cd the_feedstock
    - conda smithy rerender
    - conda smithy lint --conda-forge

about:
  home: https://github.com/conda-forge/conda-smithy
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: The tool for managing conda-forge feedstocks

extra:
  recipe-maintainers:
    - conda-forge/core
