{% set version = "3.30.4" %}

package:
  name: conda-smithy
  version: {{ version }}

source:
  url: https://github.com/conda-forge/conda-smithy/releases/download/v{{ version }}/conda-smithy-{{ version }}.tar.gz
  sha256: 4a0373e84316cf4bb711779a258a200f778daf3e6cfc51cae8a5df383e3383dd

build:
  number: 1
  noarch: python
  string: unix_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [unix]
  string: win_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}   # [win]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
    - rm -f "${PREFIX}/bin/conda"           # [not win]
    - del /f /q "%PREFIX%\\Scripts\\conda"  # [win]
  entry_points:
    - feedstocks = conda_smithy.feedstocks:main
    - conda-smithy = conda_smithy.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=45
    - setuptools-scm >=7
    - tomli >=1.0.0
  run:
    - __unix                          # [unix]
    - __win                           # [win]
    - python >=3.6
    - setuptools
    - conda >=4.2
    - conda-build >=3.18.3
    - conda-package-handling >=1.9.0
    - jinja2
    - requests
    - pycryptodome
    - gitpython
    - git                             # [unix]
    - m2-git                          # [win]
    - pygithub >=2,<3
    - ruamel.yaml >=0.16
    - conda-forge-pinning
    - vsts-python-api
    - toolz
    - scrypt
    - license-expression
    - libarchive
    - tomli >=1.0.0  # for python <3.11, can remove in the future
    - cirun >=0.30
  run_constrained:
    # For more details about `shellcheck`, please see this issue.
    # xref: https://github.com/conda-forge/conda-smithy-feedstock/issues/248
    - shellcheck

test:
  imports:
    - conda_smithy
    - conda_smithy.ci_register
    - conda_smithy.configure_feedstock
  commands:
    - conda smithy --help

about:
  home: https://github.com/conda-forge/conda-smithy
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: The tool for managing conda-forge feedstocks

extra:
  recipe-maintainers:
    - conda-forge/core
