{% set version = "3.46.0" %}

package:
  name: conda-smithy
  version: {{ version }}

source:
  url: https://github.com/conda-forge/conda-smithy/releases/download/v{{ version }}/conda_smithy-{{ version }}.tar.gz
  sha256: 81c8bd80d0741dda3642fe22c008ffa68bd64414ec88e24f12578decc4145a94

build:
  number: 0
  noarch: python
  string: {{ "win" if win else "unix" }}_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
    - rm -f "${PREFIX}/bin/conda"           # [not win]
    - del /f /q "%PREFIX%\\Scripts\\conda"  # [win]
  entry_points:
    - feedstocks = conda_smithy.feedstocks:main
    - conda-smithy = conda_smithy.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=45
    - setuptools-scm >=8.1
    - tomli >=1.0.0
  run:
    - __unix                          # [unix]
    - __win                           # [win]
    - python >={{ python_min }}
    - setuptools
    - conda >=4.2
    - conda-build >=24.3
    - conda-package-handling >=1.9.0
    - jinja2
    - requests
    - pycryptodome
    - gitpython
    - pygit2
    - git                             # [unix]
    # TODO: Both `git` & `m2-git` on Windows have problems.
    #       For now, install neither. Hopefully we can find
    #       a better solution in the future.
    #- m2-git                          # [win]
    - pygithub >=2,<3
    - ruamel.yaml >=0.16
    - conda-forge-pinning
    - vsts-python-api
    - toolz
    - scrypt
    - license-expression
    - libarchive
    - tomli >=1.0.0  # for python <3.11, can remove in the future
    - backports.strenum
    - cirun >=0.30
    - exceptiongroup
    - jsonschema
    - rattler-build-conda-compat >=1.2.0,<2.0.0a0
  run_constrained:
    # For more details about `shellcheck`, please see this issue.
    # xref: https://github.com/conda-forge/conda-smithy-feedstock/issues/248
    - shellcheck

test:
  imports:
    - conda_smithy
    - conda_smithy.ci_register
    - conda_smithy.configure_feedstock
  requires:
    # no python_min here to be able to test smithy as a downstream (e.g. conda-feedstock)
    - python
    - mock
    - pytest
    - pytest-cov
    - pydantic >=2,<3
    - conda-forge-tick      # [unix]
    - conda-souschef
    - conda-recipe-manager <=0.4.0
  source_files:
    - tests/
    - pyproject.toml  # for pytest config bits
  commands:
    - conda smithy --help
    # Run the tests but ignore tests that fail at the time of writing.
    # These environment variables are removed because they prevent the
    # tests from running correctly. See https://github.com/conda-forge/conda-smithy/pull/2162
    # This is a temporary workaround until a smithy with the fix is released.
    - unset CONDA_PY
    - unset CONDA_NPY
    - unset CONDA_R
    - unset CONDA_LUA
    - unset CONDA_PERL
    - >-
      pytest tests
      --ignore tests/test_anaconda_token_rotation.py
      --ignore tests/test_cli.py
      -k "not test_maintainer_team_exists and not test_github_actions_pins and not test_maintainer_exists and not test_lint_recipe_parses_spacing"

about:
  home: https://github.com/conda-forge/conda-smithy
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: The tool for managing conda-forge feedstocks

extra:
  recipe-maintainers:
    - conda-forge/core
