conda_forge_output_validation: true
conda_build:
  pkg_format: '2'
github:
  branch_name: main
  tooling_branch_name: main
noarch_platforms:
- linux_64
- win_64
provider:
  linux_64: github_actions
  win_64: github_actions
