travis:
  secure:
    BINSTAR_TOKEN: NTyjsJybSJKbeXjowgfPk8ZicAZNYrAcWxlOAzdi9eLaXm2HrVB+RykkH+dNimXtJTuGKHsijjzqd6YeaSm48FDUx+TsgV9wgsGlCrjijewvmQDUH962iqcTKy8dOUzNWD/+ohtpitGHuSw1r/39dXbCSOAn3kiHlU+zmwjv5uQ3EhfthmIGYY6j9k8MeeI7PHnIX+Sao6RQ0KSJNrgTW/QD2nPa3Ij+Y+qNv4UGXJqOs0pH1Ev1Mgi9pSkJHT/pR/yBcyPjaK5mB2ntVjEQy2XfGWn0RVPC8A4Q/1YnAcIyevzRn/wffmgn8UhjBvOtDEZI9wqotfIpPwMJEKVaERgcH5iYfahkKbhbm5yPn3ByKymKeZ5dDGYOhsQHDS2oSU8xUwJvgTcKQT4k0kh84MZF368+xz9JkWU8Mu6Rku1C85y4+n0jGp2X6++kHcumq7Hbt8b6t+gipZggaKpSr1FQrEvbnfDIsoxhxvr3juFwoPi28IuEx9/s8vGMIhVGnQFP7ZPL2igYShCuH/6+dv0ysZ7Ht+dI/bRk5we9YMxf14hghQoJjMLMPvSG66lSjudnTYkIu/5F03nakSRcOlibBc1OVMvzPfEEFvDkA4EfJYnuz5BMkyiCJ16PpBqR1Wj9n39in/+4MwFZwwddmZ+A7kvvRAESS84v9tLFUZQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
